urls.py
from coffin.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'tickets.views.whiteboard', name='whiteboard'),
    url(r'^min$', 'tickets.views.whiteboard_min', name='whiteboard_min'),
    url(r'^refresh$', 'tickets.views.refresh', name='refresh'),
    url(r'^modal/(?P<ticket_no>\d+)$', 'tickets.views.modal', name='modal'),
    url(r'^status_update/(?P<ticket_no>\d+)/(?P<status_id>\d+)$', 'tickets.views.status_update', name='status_update')
    

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

tickets/models.py
from django.db import models

class User(models.Model):
	""" A user """
	name=models.CharField(max_length=255)

	def __unicode__(self):
		return unicode(self.name)

class Status(models.Model):
	"""A ticket status"""
	number=models.IntegerField()
	name=models.CharField(max_length=255)

	def __unicode__(self):
		return unicode(self.name)

class Category(models.Model):
	"""A ticket status"""
	number=models.IntegerField()
	name=models.CharField(max_length=255)

	def __unicode__(self):
		return unicode(self.name)

class Ticket(models.Model):
	"""A ticket"""
	number=models.IntegerField()
	summary=models.CharField(max_length=255)
	status=models.ForeignKey(Status,blank=True,null=True)
	assignee=models.ForeignKey(User,blank=True,null=True)
	category=models.ForeignKey(Category,blank=True,null=True)

	def __unicode__(self):
		return unicode(self.number)

	def __save__(self,*args,**kwargs):
		"""Replicate the saved changes to remote system"""
		#Only save local changes if remote save is successful, otherwise throw error
		super(Ticket,self).__save__(*args,**kwargs)
		pass

tickets/forms.py
from django import forms
from tickets.models import Ticket

class UpdateTicketForm(forms.ModelForm):

    comment = forms.CharField(max_length=1000,widget=forms.Textarea(attrs={'cols': 70, 'rows': 4}),required=False)

    class Meta:
        model = Ticket
        fields = ['summary','assignee','status','category']

    def __init__(self,*args,**kwargs):
        super(UpdateTicketForm,self).__init__(*args,**kwargs)
        self.fields['summary'].label = "Summary <i class='icon-info-sign'></i>"
        self.fields['assignee'].label = "Assign <i class='icon-user'></i>"
        self.fields['status'].label = "Status <i class='icon-flag'></i> "
        self.fields['category'].label = "Category <i class='icon-th-large'></i>"
        self.fields['comment'].label = "Comment <i class='icon-comment'></i> "


    def __save__(self,*args,**kwargs):
        if 'comment' in self.cleaned_data:
            #TODO: Update this separately
            del self.cleaned_data['comment']
        super(UpdateTicketForm,self).__save__(*args,**kwargs)

tickets/views.py
from tickets.models import Ticket, User, Status
from django.http import HttpResponse
from django.conf import settings
from django.core.context_processors import csrf
from kaizen.djangojinja2 import render_to_response, render_to_string
from tickets.helpers import get_tickets
from tickets.forms import UpdateTicketForm

def whiteboard(request, *args, **kwargs):
	"""The default whiteboard view"""
	context = {}
	context['tickets'] = Ticket.objects.all()
	context['users'] = User.objects.all()
	statuses = Status.objects.all()
	#'New' in ordering makes it very long
	ordering = getattr(settings,'STATUS_ORDERING')
	context['statuses'] = [statuses.get(name=ordered_name) for ordered_name in ordering]
	context['ticket_url_prefix'] = getattr(settings,'TICKET_URL_PREFIX')
	template = 'whiteboard.html'
	return render_to_response(template,context,request)

def whiteboard_min(request, *args, **kwargs):
	return whiteboard(request, condensed=True, *args, **kwargs)

def refresh(request, *args, **kwargs):
	"""Update the local tickets"""
	get_tickets()
	return whiteboard(request)

def modal(request, ticket_no=None, *args, **kwargs):
	"""Return a modal dialog via AJAX"""
	context = {}
	ticket = Ticket.objects.get(number=ticket_no)
	if request.method == 'POST':
		form = UpdateTicketForm(request.POST, instance=ticket)
		if form.is_valid():
			form.save()
			return HttpResponse('OK')
	else:
		form = UpdateTicketForm(instance=ticket)
	context['form'] = form
	context['ticket'] = ticket
	context['users'] = User.objects.all()
	context.update(csrf(request))
	template = 'modal.html'
	return HttpResponse(render_to_string(template,context=context,request=request))

def status_update(request, ticket_no=None, status_id=None, *args, **kwargs):
	"""Update the status by dragging a ticket across columns"""
	ticket = Ticket.objects.get(number=ticket_no)
	status = Status.objects.get(id=status_id)
	ticket.status = status
	ticket.save()
	return HttpResponse()

templates/modal.html
<script type="text/javascript">
  /*<![CDATA[*/
  jQuery(function() {
      var form = jQuery("#modal_form");
      form.submit(function(e) {
          jQuery("#sendbutton").attr('disabled', true)
          jQuery("#sendwrapper").prepend('<span>Sending message, please wait... </span>')
          $.post(form.attr('action'), form.serializeArray(), function(data) {
            if (data=="OK"){
              $('#ticketModal').modal('hide');
            }
            else{
              $('#ticketModal').html(data);
            }
          });

          jQuery("#ajaxwrapper").load(
              form.attr('action') + ' #ajaxwrapper',
              form.serializeArray(),
              function(responseText, responseStatus) {
                  jQuery("#sendbutton").attr('disabled', false)
              }
          );
          e.preventDefault(); 
      });
  });
  /*]]>*/
  </script> 

 <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h4>#{{ticket.number}} {{ticket.summary}}</h4>
  </div>
  

<form id="modal_form" class="form-horizontal" action="{% url modal ticket_no=ticket.number %}" method="post">
<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
  <div class="modal-body">
   <fieldset>
    <legend>Change ticket</legend>
    {% for field in form %}
<div class="control-group">
  {{ field.errors|safe }}
      <label class="control-label" for="{{field.html_name}}">{{ field.label|safe }}</label>

      <div class="controls">
        {{field|safe}}
       
      </div>
    </div>
    {% endfor %}    
     </fieldset>

  </div>
  <div class="modal-footer">
    <input type="submit" class="btn btn-primary" value="Save changes" />
    <a href="#" data-dismiss="modal" class="btn">Close</a>
  </div>
  </form>

templates/whiteboard.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<link type="text/css" href="/static/css/hot-sneaks/jquery-ui-1.8.18.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="/static/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui-1.8.18.custom.min.js"></script>
<link rel="stylesheet/less" type="text/css" href="/static/less/bootstrap.less">
<script src="/static/js/less-1.2.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/js/bootstrap-modal.js"></script>
<script>
	function fixHeight(jQuerySelector) {
		var heighest = -1, items = jQuerySelector;
		if (items.length > 0) {
			items.each(function (index) {
				$(this).css("height", "auto");
				heighest = Math.max(heighest, $(this).height());
			});
			items.each(function (index) {
				$(this).height(heighest);
			});
		}
	}

	$(document).ready(function(){
		$('.row').each(function(){
			fixHeight($(this).find('.column'));
		});
		$('.user_filter').click(function() {
			var username = $(this)[0].attributes['user'].value;
			$(".user_filter").each(function() {
				$(this).removeClass('btn-success');
			});
			$(this).addClass('btn-success');
			$(".user_row").each(function() {
				if ($(this).hasClass(username)){
					$(this).show();
				}
				else {
					$(this).hide();
				}
			});
		});
		$('.tickets').each(function(){$(this).sortable({
			revert: true
		})});
		$('.sticky').each(function(){$(this).draggable({
			stack: '.tickets',
			stop: function(event,ui){
				var tleft=ui.offset.left;
				var ticket_no = $(this)[0].attributes['ticket_no'].value;
				$('.status_headers').each(function() {
					var ileft = $(this).position().left;
					var iright = ileft + $(this).width()+32;
					if(ileft<tleft&&tleft<iright){
						var status_id = $(this)[0].attributes['status_id'].value
						{% set status_id = status_id %}
						$.get("/status_update/"+ticket_no+"/"+status_id);
					}
				});
			}
		});});
		$('.quick-task').click(function(){
			$this = $(this);
			var ticket_no = $(this)[0].attributes['ticket_no'].value;
			$.get('/modal/'+ticket_no, function(data) {
				$('#ticketModal').html(data);
				$('#ticketModal').modal();
		}	);
		});
		$('.sticky').hover(function(){$(this).find('.quick-task').fadeIn(100)},function(){$(this).find('.quick-task').fadeOut(100)});
	});

</script>
</head>
<body>
	<div class="navbar kaizen-fixed-top">
	
	<div class="btn-toolbar">
		<div class="btn-group">
</div>
<div class="btn-group">
	<a class="btn btn-primary" user="all" href="javascript:void(0)" class="user_filter">all</a>
{% for user in users %}
	<a class="btn user_filter" user="{{user.name}}" href="javascript:void(0)" class="user_filter">@{{user.name}}</a>
{% endfor %}
	<a class="btn btn-inverse" href="javascript:void(0)">released</a>
</div>
</div>
</div>
<div id="kaizen">
	<div class="row header">
		<div class="span2 column">
			<span class="logo">改善 Kaizen<span class="version">v0.1</span></span>
		</div>
		{% for status in statuses %}
			<div class="span3 column status_headers" status_id="{{ status.id }}">
				<h3>{{ status.name }}</h3>
			</div>
		{% endfor %}
	</div>
{% for user in users %}
	<div class="row user_row {{user.name}}">
		<div class="span2 column">
			<span class="username_column">@{{ user.name }}</span>
		</div>
		{% for status in statuses %}
			<div class="span3 column {{ loop.cycle('odd', 'even') }}">
				<div class="tickets">
					{% for ticket in user.ticket_set.filter(status=status) %}
						<div class="sticky" ticket_no="{{ticket.number}}">
							<div class="sticky_number">
							<a target="_blank" href="{{ticket_url_prefix}}{{ticket.number}}">
								<strong>#{{ticket.number}}</strong>
							</a>
						</div>
					          <a class="quick-task" style="display:none;" ticket_no="{{ticket.number}}" href="javascript:void(0)"><i class="icon-pencil"></i></a></a>
							<span class="sticky_text">
									{{ticket.summary}}
							</span>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endfor %}
	</div>	
{% endfor %}
</div>

<div class="modal hide" id="ticketModal">
</div>

</body>
</html>